name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker
        run: docker login -u halftome -p ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push the Docker images
        run: docker build -t halftome/buildx-builder --push .
